-- CREATE TABLE ot.persons(
--     person_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
--     first_name VARCHAR2(50) NOT NULL,
--     last_name VARCHAR2(50) NOT NULL,
--     PRIMARY KEY(person_id)
-- );

CREATE TABLE AdoptablePets (
    person_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY(person_id)
);

id NUMBER generated BY DEFAULT AS identity PRIMARY KEY,
name VARCHAR2(50 CHAR) NOT NULL,
breed_id NUMBER,
weight NUMBER(6,2),
height NUMBER(5,2),
available_date DATE,
status status VARCHAR2(5 CHAR) NOT NULL CHECK(status IN ('Available', 'Adopted')),
adoption_date DATE,
adoption_cost NUMBER(6,2),
adopter_id NUMBER,
type_of_animal_id NUMBER,
FOREIGN KEY(group_id) REFERENCES supplier_groups(group_id),
FOREIGN KEY(group_id) REFERENCES supplier_groups(group_id),
FOREIGN KEY(group_id) REFERENCES supplier_groups(group_id),
PRIMARY KEY(id)