-- @ Lab 7
-- Turn in your sql for the following:

-- Create a table called Lab7 with 4 columns: id, description, employee_id, and name
-- Put a primary key out of line constraint on this table on the id column and a not null in line constraint on the description column.
CREATE TABLE Lab7 (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(25 CHAR),
    description VARCHAR2(500 CHAR) NOT NULL,
    employee_id NUMBER,
    CONSTRAINT lab7_pk PRIMARY KEY (id)
);

-- to see progress
DESCRIBE Lab7;

-- Drop the name column from your Lab7 table.
ALTER TABLE Lab7
DROP COLUMN name;

-- to see progress
DESCRIBE Lab7;

-- Alter your table to change employee_id to be a foreign key to the HR.EMPLOYEES table.
-- Switched tables due to permission restrictions
CREATE TABLE employees AS SELECT * FROM HR.EMPLOYEES;
ALTER TABLE employees MODIFY employee_id PRIMARY KEY;
ALTER TABLE Lab7
ADD FOREIGN KEY (employee_id) REFERENCES employees(employee_id);

-- Create a view over your Lab7 table called Lab7_View with the three columns but restrict to only records having employee_id greater than 50.
CREATE VIEW Lab7_View AS
    SELECT id, description, employee_id
    FROM Lab7
    WHERE id > 50;

-- Drop your table and view.
DROP VIEW Lab7_View;
DROP TABLE Lab7;
DROP TABLE employees;