-- database tables
-- @ TypeOfAnimals
CREATE TABLE TypeOfAnimals (
    type_of_animal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_of_animal VARCHAR2(25 CHAR) NOT NULL UNIQUE
);

-- @ Staff
CREATE TABLE Staff (
    staff_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_first_name VARCHAR2(25 CHAR) NOT NULL,
    staff_last_name VARCHAR2(25 CHAR) NOT NULL,
    staff_address VARCHAR2(100 CHAR) NOT NULL,
    staff_state CHAR(2 CHAR) NOT NULL,
    staff_city VARCHAR2(50 CHAR) NOT NULL,
    staff_zip NUMBER(5) NOT NULL,
    staff_phone_number VARCHAR2(20 CHAR) NOT NULL,
    staff_email VARCHAR2(150 CHAR) NOT NULL,
    staff_is_active NUMBER(1) DEFAULT 1,
    staff_note VARCHAR2(500 CHAR),
    created_by NUMBER,
    created_date DATE NOT NULL,
    updated_by NUMBER,
    updated_date DATE,
    FOREIGN KEY(updated_by) REFERENCES Staff(staff_id)
);

-- @ Breeds
CREATE TABLE Breeds (
    breed_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    breed_name VARCHAR2(50 CHAR) NOT NULL UNIQUE,
    type_of_animal_id NUMBER NOT NULL,
    FOREIGN KEY(type_of_animal_id) REFERENCES TypeOfAnimals(type_of_animal_id)
);

-- @ Adopters
CREATE TABLE Adopters (
    adopter_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adopters_first_name VARCHAR2(25 CHAR) NOT NULL,
    adopters_last_name VARCHAR2(25 CHAR) NOT NULL,
    adopters_address VARCHAR2(100 CHAR) NOT NULL,
    adopters_state CHAR(2 CHAR) NOT NULL,
    adopters_city VARCHAR2(50 CHAR) NOT NULL,
    adopters_zip NUMBER(5) NOT NULL,
    adopters_phone_number VARCHAR2(20 CHAR) NOT NULL,
    adopters_email VARCHAR2(150 CHAR) NOT NULL,
    adopter_is_active NUMBER(1) DEFAULT 1,
    adopters_note VARCHAR2(500 CHAR),
    created_by NUMBER NOT NULL,
    created_date DATE NOT NULL,
    updated_by NUMBER,
    updated_date DATE,
    FOREIGN KEY(created_by) REFERENCES Staff(staff_id),
    FOREIGN KEY(updated_by) REFERENCES Staff(staff_id)
);

-- @ Locations
CREATE TABLE Locations (
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name VARCHAR2(50 CHAR) NOT NULL,
    location_address VARCHAR2(100 CHAR) NOT NULL,
    location_state CHAR(2 CHAR) NOT NULL,
    location_city VARCHAR2(50 CHAR) NOT NULL,
    location_zip NUMBER(5) NOT NULL,
    location_phone_number VARCHAR2(20 CHAR) NOT NULL,
    location_email VARCHAR2(150 CHAR) NOT NULL,
    location_is_active NUMBER(1) DEFAULT 1,
    location_note VARCHAR2(500 CHAR),
    created_by NUMBER NOT NULL,
    created_date DATE NOT NULL,
    updated_by NUMBER,
    updated_date DATE,
    FOREIGN KEY(created_by) REFERENCES Staff(staff_id),
    FOREIGN KEY(updated_by) REFERENCES Staff(staff_id)
);

    CREATE TABLE StaffAtLocation (
        staff_id NUMBER NOT NULL,
        location_id	NUMBER NOT NULL,
        primary key (staff_id, location_id),
        FOREIGN KEY(staff_id) REFERENCES Staff(staff_id),
        FOREIGN KEY(location_id) REFERENCES Locations(location_id)
    );

-- @ PetStatus
CREATE TABLE PetStatus (
    pet_status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_status VARCHAR2(25 CHAR) NOT NULL UNIQUE
);

-- @ AdoptablePets
CREATE TABLE AdoptablePets (
    adoptable_pet_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adoptable_pet_name VARCHAR2(50 CHAR) NOT NULL,
    breed_id NUMBER NOT NULL,
    weight NUMBER(6,2),
    height NUMBER(5,2),
    available_date DATE,
    pet_status_id NUMBER DEFAULT 1,
    location_id NUMBER NOT NULL,
    adoptable_pet_note VARCHAR2(500 CHAR),
    created_by NUMBER NOT NULL,
    created_date DATE NOT NULL,
    updated_by NUMBER,
    updated_date DATE,
    FOREIGN KEY(breed_id) REFERENCES Breeds(breed_id),
    FOREIGN KEY(pet_status_id) REFERENCES PetStatus(pet_status_id),
    FOREIGN KEY(location_id) REFERENCES Locations(location_id),
    FOREIGN KEY(created_by) REFERENCES Staff(staff_id),
    FOREIGN KEY(updated_by) REFERENCES Staff(staff_id)
);

    CREATE TABLE Adoptions (
        adoptable_pet_id NUMBER NOT NULL,
        adopter_id NUMBER NOT NULL,
        adoption_date DATE NOT NULL,
        adoption_cost NUMBER(6,2) NOT NULL,
        staff_id NUMBER NOT NULL,
        location_id NUMBER NOT NULL,
        primary key (adoptable_pet_id, adopter_id),
        FOREIGN KEY(adoptable_pet_id) REFERENCES AdoptablePets(adoptable_pet_id),
        FOREIGN KEY(adopter_id) REFERENCES Adopters(adopter_id),
        FOREIGN KEY(staff_id) REFERENCES Staff(staff_id),
        FOREIGN KEY(location_id) REFERENCES Locations(location_id)
    );

-- @ Vaccinations
CREATE TABLE Vaccinations (
    vaccination_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaccination_name VARCHAR2(75 CHAR) NOT NULL,
    type_of_animal_id NUMBER NOT NULL,
    vaccination_is_active NUMBER(1) DEFAULT 1,
    vaccination_note VARCHAR2(500 CHAR),
    created_by NUMBER NOT NULL,
    created_date DATE NOT NULL,
    updated_by NUMBER,
    updated_date DATE,
    FOREIGN KEY(created_by) REFERENCES Staff(staff_id),
    FOREIGN KEY(updated_by) REFERENCES Staff(staff_id),
    FOREIGN KEY(type_of_animal_id) REFERENCES TypeOfAnimals(type_of_animal_id)
);

    CREATE TABLE AnimalVaccinations (
        vaccination_id NUMBER NOT NULL,
        adoptable_pet_id NUMBER NOT NULL,
        date_administered DATE NOT NULL,
        staff_id NUMBER NOT NULL,
        location_id NUMBER NOT NULL,
        primary key (vaccination_id, adoptable_pet_id),
        FOREIGN KEY(vaccination_id) REFERENCES Vaccinations(vaccination_id),
        FOREIGN KEY(adoptable_pet_id) REFERENCES AdoptablePets(adoptable_pet_id),
        FOREIGN KEY(staff_id) REFERENCES Staff(staff_id),
        FOREIGN KEY(location_id) REFERENCES Locations(location_id)
    );

-- additional constraints
ALTER TABLE AdoptablePets ADD CONSTRAINT ck_weight CHECK (weight BETWEEN 0 and 3000);
ALTER TABLE AdoptablePets ADD CONSTRAINT ck_height CHECK (height BETWEEN 1 and 108);
ALTER TABLE Adopters ADD CONSTRAINT ck_adopters_email CHECK (
   adopters_email LIKE '%@%.%' 
   AND adopters_email NOT LIKE '@%' 
   AND adopters_email NOT LIKE '%@%@%'
);
ALTER TABLE Adopters ADD CONSTRAINT ck_active CHECK (adopter_is_active BETWEEN 0 and 1);
ALTER TABLE Vaccinations ADD CONSTRAINT ck_vaccine_active CHECK (vaccination_is_active BETWEEN 0 and 1);
ALTER TABLE Staff ADD CONSTRAINT ck_staff_email CHECK (
   staff_email LIKE '%@%.%' 
   AND staff_email NOT LIKE '@%' 
   AND staff_email NOT LIKE '%@%@%'
);
ALTER TABLE Staff ADD CONSTRAINT ck_staff_is_active CHECK (staff_is_active IN (0, 1));
ALTER TABLE Locations ADD CONSTRAINT ck_location_email CHECK (
   location_email LIKE '%@%.%' 
   AND location_email NOT LIKE '@%' 
   AND location_email NOT LIKE '%@%@%'
);
ALTER TABLE Locations ADD CONSTRAINT ck_location_active CHECK (location_is_active IN (0, 1));

-- additional indexes
-- potential other indexes that may boost performance although may not be needed on such a small dataset as ours
CREATE INDEX index_adoptable_pet_name ON AdoptablePets(adoptable_pet_name);
CREATE INDEX index_available_date ON AdoptablePets(available_date);
CREATE INDEX index_adoption_date ON Adoptions(adoption_date);
CREATE INDEX index_adopters_first_name ON Adopters(adopters_first_name);
CREATE INDEX index_adopters_last_name ON Adopters(adopters_last_name);
CREATE UNIQUE INDEX index_adopters_email ON Adopters(adopters_email);
CREATE INDEX index_date_administered ON AnimalVaccinations(date_administered);
CREATE INDEX index_staff_first_name ON Staff(staff_first_name);
CREATE INDEX index_staff_last_name ON Staff(staff_last_name);
CREATE UNIQUE INDEX index_staff_email ON Staff(staff_email);
CREATE UNIQUE INDEX index_location_email ON Locations(location_email);